# DataSource Config
spring:
  datasource:
    #    driver-class-name: com.mysql.cj.jdbc.Driver
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql://139.224.8.35:3306/eblog?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: root
  freemarker:
    settings:
      classic_compatible: true
      datetime_format: yyyy-MM-dd HH:mm
      number_format: 0.##
  redis:
    host: 139.224.8.35
    port: 6379
    password: root
  data:
    elasticsearch:
      cluster-name: kobe
      cluster-nodes: 139.224.8.35:9300
      repositories:
        enabled: true
  rabbitmq:
    username: root
    password: root
    host: 139.224.8.35
    port: 5672